import streamlit as st


st.set_page_config(page_title="Home | Sales Analyzer", layout="wide")

st.sidebar.markdown('Developed by Yago Lopes - [LinkedIn](https://www.linkedin.com/in/yagolopes/)')

st.markdown('# Welcome to the Sales Analyzer')

st.divider()

st.markdown(
    '''
    This project is an **interactive template for sales analysis**, built in Python, and can be easily adapted to different markets and datasets.

    It leverages three main libraries:

    - `pandas`: for tabular data manipulation
    - `plotly`: for interactive charts and dynamic visualizations
    - `streamlit`: to build this interactive web app you're using right now

    The data used was generated by the script 'gerador_de_vendas.py' included with the project's source code. You can explore the data in the Tables page.

    The goal of this project is to provide a simple and effective tool for sales analysis, allowing users to explore and visualize their data in an intuitive way.
    '''
)